#!/bin/sh

export C_INCLUDE_PATH=${PREFIX}/include
export LIBRARY_PATH=${PREFIX}/lib
export LD_LIBRARY_PATH=${PREFIX}/lib

cd contrib

cmake . -DBUILD_TYPE=LIBSVM
#cmake . -DBUILD_TYPE=XERCESC
#cmake . -DBUILD_TYPE=GSL
cmake . -DBUILD_TYPE=COINOR
#cmake . -DBUILD_TYPE=BZIP2
#cmake . -DBUILD_TYPE=ZLIB
#cmake . -DBUILD_TYPE=GLPK
#cmake . -DBUILD_TYPE=EIGEN
cmake . -DBUILD_TYPE=WILDMAGIC
cmake . -DBUILD_TYPE=SEQAN
#cmake . -DBUILD_TYPE=BOOST -DNUMBER_OF_JOBS=4
cd ..

mkdir build
cd build
ORIGIN='$ORIGIN'
export ORIGIN
LDFLAGS='-Wl,-rpath,$${ORIGIN}/../lib' 
cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX -DHAS_XSERVER=OFF -DENABLE_TUTORIALS=OFF -DENABLE_STYLE_TESTING=OFF -DENABLE_UNITYBUILD=OFF -DWITH_GUI=OFF -DBoost_INCLUDE_DIR=$PREFIX/include -DBoost_LIBRARY_DIRS=$PREFIX/lib -DBoost_LIBRARIES=$PREFIX/lib -DBoost_LIB_VERSION=1.57.0 -DBoost_DEBUG=ON -DBOOST_LIBRARYDIR=$PREFIX/lib/ -DBOOST_USE_STATIC=OFF -DNUMBER_OF_JOBS=4

make -j4 TOPP ##UTILS OpenMS
make install
